{% set version = "1.13.1" %}

package:
  name: tensorflow-{{ variant }}
  version: {{ version }}.db1

build:
  number: 0
  skip: True  # [not x86_64]

requirements:
  run:
    - tensorflow =={{ version }}.db1
    - _tflow_select =={{ select_version }}

test:
  imports:
    - tensorflow
    - tensorboard
  commands:
    - tensorboard --help

about:
  summary: Metapackage for selecting a TensorFlow variant.
